server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-braker-resilience4j
          uri: https://github.com/Alan-Mejia/Prueba2MS
          search-paths: config-data
  application:
    name: config-service
